library(dplyr)
source("R/adl_realism.R")
stopifnot(identical(adl_realism_status(c("Out","O","Bye","Questionable","IR","Inactive",NA),rep(FALSE,7)),c("INA","INA","INA","ACT","MISPL","ACT","ACT")),adl_realism_status("Questionable",TRUE)=="INA")
stopifnot(all(adl_realism_excluded(c("S","H","I","Suspended","Holdout","IR","IR-R","IR-PUP","IR-NFI"))), adl_realism_status("IR-PUP",TRUE)=="MISPL", !adl_realism_excluded("Out"))
p<-readr::read_csv("data/nfl_realism/adl_players.csv.gz",col_types=readr::cols(.default=readr::col_character(),season=readr::col_integer(),week=readr::col_integer()),show_col_types=FALSE)
w<-readr::read_csv("data/nfl_realism/adl_weekly.csv",show_col_types=FALSE)
counts<-p |> filter(roster_status=="ROSTER") |> count(season,week,franchise_id,name="raw")
check<-w |> group_by(season,week,franchise_id) |> summarise(total=sum(players),.groups="drop") |> left_join(counts,by=c("season","week","franchise_id"))
stopifnot(nrow(check)==4*17*32,all(check$total==check$raw),!anyDuplicated(p[,c("season","week","franchise_id","player_id")]),all(w$players>=0),any(w$players==0))
c<-readr::read_csv("data/nfl_realism/adl_coverage.csv",show_col_types=FALSE)
stopifnot(nrow(c)==68,all(c$franchises==32),all(c$report_rows>0))
cat("ADL historical membership, classification, zero cells and 2,176 franchise-week totals verified.\n")
