const fs=require('fs'),vm=require('vm'),assert=require('assert');
const data=JSON.parse(fs.readFileSync('data/parity/report.json','utf8')),elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',value:'',hidden:false,handlers:{},setAttribute(){},addEventListener(event,fn){this.handlers[event]=fn;}});return elements.get(id);};
element('parity-data').textContent=JSON.stringify(data);
vm.runInNewContext(fs.readFileSync('R/parity_report.js','utf8'),{document:{getElementById:element,querySelectorAll:()=>[]},location:{hash:'#parity-report'},window:{addEventListener(){}}});
const change=(id,value)=>{element('parity-'+id).value=value;element('parity-'+id).handlers.change();};
assert(element('parity-sample').textContent.includes('160 team-seasons'));
assert(element('parity-short-scatter').innerHTML.includes('data-league="NFL12"'));
assert(element('parity-short-scatter').innerHTML.includes('data-league="ADL"'));
assert(element('parity-long-scatter').innerHTML.includes('data-league="NFL"'));
assert(element('parity-long-scatter').innerHTML.includes('data-league="ADL Reg Season"'));
assert((element('parity-short-scatter').innerHTML.match(/<circle /g)||[]).length===256);
assert((element('parity-metrics').innerHTML.match(/<tr>/g)||[]).length===5);
assert((element('parity-mobility-metrics').innerHTML.match(/<tr>/g)||[]).length===4);
assert(element('parity-mobility-sample').textContent.includes('128 franchise transitions'));
for(const p of data.pooled)assert(element('parity-mobility-metrics').innerHTML.includes(p.correlation.toFixed(2)));
change('minimum','2023');change('maximum','2024');
assert(element('parity-sample').textContent.includes('64 team-seasons'));
assert(element('parity-mobility-sample').textContent.includes('32 franchise transitions'));
assert(!element('parity-movements').innerHTML.includes('2022→2023'));
assert(element('parity-movements').innerHTML.includes('2023→2024'));
change('minimum','2025');
assert(element('parity-maximum').value===2025);
assert(element('parity-transition-views').hidden);
assert(element('parity-mobility-sample').textContent.includes('at least two years'));
element('parity-ytd').handlers.click();
assert(element('parity-range-controls').hidden);
assert(element('parity-context').textContent.includes('2026 season-to-date'));
assert(element('parity-movements').innerHTML.includes('2025→2026'));
assert(!element('parity-metrics').innerHTML.includes('NaN'));
assert(!element('parity-mobility-metrics').innerHTML.includes('β'));
assert(element('parity-mobility-metrics').innerHTML.includes('Record persistence · r'));
console.log('Parity ranges verified: full pool, restricted adjacent transitions, one year, crossed endpoints and separate YTD.');
